services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: thesis_db
      MYSQL_USER: thesis_user
      MYSQL_PASSWORD: thesis_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]
    volumes:
      - ./backend:/app
      - staticfiles:/app/backend/staticfiles
      - mediafiles:/app/backend/media
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=thesis_db
      - DATABASE_USER=thesis_user
      - DATABASE_PASSWORD=thesis_pass
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DEBUG=False
      # Email Configuration
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=jedd709999@gmail.com
      - EMAIL_HOST_PASSWORD=dxfw tcag uctr cmrd
      - DEFAULT_FROM_EMAIL=jedd709999@gmail.com
      - GOOGLE_CLIENT_ID=47765248404-3cio0hk7oasn17dfg86grrf3sh69okgg.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8002:8000"  # Changed from 8001:8000 to 8002:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=47765248404-3cio0hk7oasn17dfg86grrf3sh69okgg.apps.googleusercontent.com
        - VITE_GOOGLE_CLIENT_SECRET=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
        - VITE_API_BASE_URL=http://localhost:8002/api
        - VITE_GOOGLE_REDIRECT_URI=http://localhost:8080/auth/complete/google-oauth2/

    volumes:
      - staticfiles:/static
      - mediafiles:/media
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_started
    environment:
      - NODE_ENV=production
      - VITE_GOOGLE_CLIENT_ID=47765248404-3cio0hk7oasn17dfg86grrf3sh69okgg.apps.googleusercontent.com
      - VITE_GOOGLE_CLIENT_SECRET=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
      - VITE_API_BASE_URL=http://localhost:8002/api
      - VITE_GOOGLE_REDIRECT_URI=http://localhost:8080/auth/complete/google-oauth2/

    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:
  staticfiles:
  mediafiles: